language: c
sudo: true
deploy:
  provider: pypi
  user: bgruening
  password:
    secure: WXZ0MK7hk5hfwmEIOHyDSOAiqQyDH/PfXBqUQ6+pQ/1iApi7iGDwHnSmMY0mSmIqksRLr1C37+E2xZKY7Ig2D7GXx3X2aSUFDZMYyhDhz2nP5qwGLNxQCSKROuVg90ArDhfl1aIPZoYK77mqfXCxP8nmnJq9xhzWNAkhjA/fypyfYV0ZlSqVYKFL7vTz0Vz+RUvizrRMtdXsceuCZ1v0bIT2BJ2zkvcggah9s2xRrEa4wTFogYFLXTOodUsfJJ8hC0TKs0eqgnxj/lFMeMuS2VE3sKE7QAOoBGvRmppd1SK6RrBpF3DnLmpW6sLsMWOMbNnvgGGbja4oJ0zTUcJ5G6YEzv9nAQTwPjf+24ZWUcmpEOMe1LrqDiqw8FePvZOAfOqrZXodFvXcI2ZXmXchgBCA2h8l9vwno5Y7gUmZVLpzsArukcr6vhwmnMerwxWFwkNljpT5DZxDE9vJ76MfneR4m5PrKZQgfpmMpAgLH8F2xwRCMpoMuq86bOm0QbI2zzkcADGvkgEFifk8Zlr0s7fJD66H570qqawEQ5PYLAhZ7zXK8AGIyy2mtDmBvZUEnXvjmsTQo4Tp1ARQzqQm8M41IEDcF92/WoMNJ21ECsiFq72qWKIdzl8Co7umVdF6sfhoTVq4Q5kTldvkvfTnK0vCExCDHI9+C3kwzplSQIM=
env:
- TRAVIS_PYTHON_VERSION=3.6
os:
- linux
- osx
jobs:
  include:
  - stage: lint
    env:
    - LINT=1
    - TRAVIS_PYTHON_VERSION=3.6
    - TRAVIS_OS_NAME=linux
    before_install:
    - curl https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -o
      miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - PATH_WITHOUT_CONDA="$PATH"
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    install:
    - conda install --yes python=3.6 flake8
    script:
    - if [[ "$LINT" == "1" ]]; then flake8 . --exclude=.venv,.build,build --ignore=E501,F403,E402,F999,F405,E712
      ; fi
before_install:
- export TEST_DATA_DIR="`pwd`/pygenometracks/test/test_data/"
- echo $TEST_DATA_DIR
- if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then
  curl https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -o miniconda.sh
  ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" && "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then curl
  https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -o miniconda.sh
  ; fi
- bash miniconda.sh -b -p $HOME/miniconda
- PATH_WITHOUT_CONDA="$PATH"
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
install:
- conda install --yes -c bioconda -c conda-forge python=$TRAVIS_PYTHON_VERSION --file
  requirements.txt
- if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then conda install --yes -c bioconda
  -c conda-forge -c defaults configparser ; fi
- python setup.py install
script:
- py.test pygenometracks --doctest-modules
