language: c
sudo: true

deploy:
  provider: pypi
  user: bgruening
  skip_existing: true
  password:
    secure: umDRCnyugr5/Tuq/81TQ9Lmk/SJBTU8BEh1cQIvHW7b0gN+DtT13Fl2DKtlZUlgXkp+aKbQs5TpBsZ+WDs8KJUVNpfflEh0cdiEG9x/olyhfe3a9i+y7WxAZBUZtzKTTwqgCRzm72S+lh7avxuJx5JRoXwhKWV4N3hvUl180jo+AjYdg3opXHFAU0IA4234k4TcMTM+z58GBNyPdH1YRZ6nwGi+S3lib6ctiNcpZRZhQ3o8gallr4Exmuqf4gmDPbLM7Rn0o+37lA43nt9gXO2oy7bvooTKYsIolXy2v7QmrE6kU6H70RhO4CdDxXqmVO2C8em+wj96W05/4pu65UhPExM6y/x1EztrMOd65+oVvXyNFt2SDPMk+mR5AjLbzhQIYyJpu23vSXvd+PLhy2OY27QzGTZ2Qpo3phBUBUrjINNHqvfteoaLADvLDXB9VngFJ+JK435t5jpGlpRHkHdpA1mtOnH7FsGSAE4MqFUA+GwH+eBqPzwBe8jhYwzPkV+9ivnGuYG7JOGp+mX5O9lhh/cQ5Wkv19Wzoj1512LRPX1Y3frw09K+tfgw0RahrAVydRnbRibO2tOtI2ulZVGTjXekYZAJKQBtG1/HlYv5xaRUaWPQPQuwnuSe1Aq4VcXt6BvFrIK5ZifKtyQkW79XUiikISFs9F0qd58DmU+A=
  on:
    tags: true
  distributions: sdist bdist_wheel
  python:
    - 3.7
    - 3.8
    - 3.9
    - 3.10
