pr:
  autoCancel: true
  
jobs:

- job: 'Linux'
  timeoutInMinutes: 0
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    matrix:
      Python36LowMatplotlib:
        python.version: '3.6'
        matplotlib.version: '3.1.1'
      Python36HighMatplotlib:
        python.version: '3.6'
        matplotlib.version: '3.3.4'
      Python37LowMatplotlib:
        python.version: '3.7'
        matplotlib.version: '3.1.1'
      Python37HighMatplotlib:
        python.version: '3.7'
        matplotlib.version: '3.4.3'
      Python38LowMatplotlib:
        python.version: '3.8'
        matplotlib.version: '3.1.1'
      Python38HighMatplotlib:
        python.version: '3.8'
        matplotlib.version: '3.4.3'

  steps:
  - bash: |
      echo "##vso[task.prependpath]$CONDA/bin"
      hash -r
    displayName: Add conda to PATH
  - bash: |
      conda config --set always_yes yes --set changeps1 no
      conda info -a
      conda create -n pygenometracks --yes -c conda-forge -c bioconda python=$(python.version) --file requirements_azure.txt
      source activate pygenometracks
      conda install --yes -c conda-forge -c bioconda pytest flake8 pytest-xdist pytest-forked
      conda install --yes -c conda-forge -c bioconda nose
      conda install --yes pathlib
      conda install --yes -c defaults -c conda-forge -c bioconda configparser
      conda install --yes -c conda-forge matplotlib=$(matplotlib.version)
      python setup.py install
    displayName: installing dependencies
  - script: |
      source activate pygenometracks
      flake8 . --exclude=.venv,.build,build --ignore=E501,F403,E402,F999,F405,E712,W503
    displayName: linting
  - script: |
      source activate pygenometracks
      py.test pygenometracks --doctest-modules -n 4
    displayName: pytest

- job: 'OSX'
  timeoutInMinutes: 0
  pool:
    vmImage: 'macOS-10.14'
  strategy:
    matrix:
      Python36LowMatplotlib:
        python.version: '3.6'
        matplotlib.version: '3.1.1'
      Python36HighMatplotlib:
        python.version: '3.6'
        matplotlib.version: '3.3.4'
      Python37LowMatplotlib:
        python.version: '3.7'
        matplotlib.version: '3.1.1'
      Python37HighMatplotlib:
        python.version: '3.7'
        matplotlib.version: '3.4.3'
      Python38LowMatplotlib:
        python.version: '3.8'
        matplotlib.version: '3.1.1'
      Python38HighMatplotlib:
        python.version: '3.8'
        matplotlib.version: '3.4.3'

  steps:
  - bash: |
      echo "##vso[task.prependpath]$CONDA/bin"
      hash -r
    displayName: Add conda to PATH
  - bash: |
      conda config --set always_yes yes --set changeps1 no
      conda info -a
      conda create -n pygenometracks --yes -c conda-forge -c bioconda python=$(python.version) --file requirements_azure.txt
      source activate pygenometracks
      conda install --yes -c conda-forge -c bioconda pytest flake8 pytest-xdist pytest-forked
      conda install --yes -c conda-forge -c bioconda nose
      conda install --yes pathlib
      conda install --yes -c defaults -c conda-forge -c bioconda configparser
      conda install --yes -c conda-forge matplotlib=$(matplotlib.version)
      python setup.py install
    displayName: installing dependencies
  - script: |
      source activate pygenometracks
      flake8 . --exclude=.venv,.build,build --ignore=E501,F403,E402,F999,F405,E712,W503
    displayName: linting
  - script: |
      source activate pygenometracks
      py.test pygenometracks --doctest-modules -n 4
    displayName: pytest
